<a href="https://colab.research.google.com/github/unnatiwaghe-sudo/python-practice-codes/blob/main/panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#CRETE ROWS INDEX AND COLUMN NAME IN DATAFRAME BY USER
import pandas  as pd
a1=[1,2,3,88]    #we create three list of array data and create datraframe then
a2=[7,0,9,8]
a3=[1,5,4,7]
list=[a1,a2,a3]
s=pd.DataFrame(list,index=["R1","R2","R3"],columns=["C1","C2","C3","C4"])   #we create column also in dataframe
print(s)

    C1  C2  C3  C4
R1   1   2   3  88
R2   7   0   9   8
R3   1   5   4   7

In [ ]:
#CREATE INDEX BY USER
import pandas  as pd
list=[1,2,3,4]
s=pd.DataFrame(list,index=["R1","R2","R3","R4"],columns=["c1"])
print(s)

    c1
R1   1
R2   2
R3   3
R4   4

In [ ]:
#CREATE ONE DATA FRAME USE LIST
import pandas  as pd
list=[1,2,3,4]
s=pd.Series(list)
print(s)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#CREATE ONE DATA FRAME USE LIST
import pandas  as pd
list=[1,2,3,4]
s=pd.DataFrame(list)
print(s)

   0
0  1
1  2
2  3
3  4

In [ ]:
#dictionary of lists example
#NOW WE CREATE DATAFRAME USING DICTIONARY
import pandas as pd
a1=["11A","12B","11C","12D"]
a2=["sanju","umesh","raju","viju"]
a3=[90,80,70,66]
dict={"Class":a1,"Name":a2,"Marks":a3}   #keys become column in dictionary
s=pd.DataFrame(dict)
print(s)

  Class   Name  Marks
0   11A  sanju     90
1   12B  umesh     80
2   11C   raju     70
3   12D   viju     66

In [ ]:
#LIST OF DICTIONARIES,,dictionary banaaya fir ek list mai dala that is list of dictionariesssss

#all values given if some values miss its shows Nan we show below example
import pandas as pd
Class12A={"Name":"Raja","Class":"12A","Marks":"90"}
Class12B={"Name":"Sanju","Class":"12B","Marks":"80","city":"nagpur"}
Class12C={"Name":"Viju","Class":"12C"}
list=[Class12A,Class12B,Class12C]
s=pd.DataFrame(list,index=["R1","R2","R3"])
print(s)

     Name Class Marks    city
R1   Raja   12A    90     NaN
R2  Sanju   12B    80  nagpur
R3   Viju   12C   NaN     NaN

In [ ]:
#create dataframe by dictionary of series
#1)
import pandas as pd
s1=pd.Series(["Raju","Sonu","Suny"])
s2=pd.Series(["12A","12B","12C"])
s3=pd.Series([90,99,88])
dict={"Name":s1,"Class":s2,"Marks":s3}
data=pd.DataFrame(dict)
print(data)

   Name Class  Marks
0  Raju   12A     90
1  Sonu   12B     99
2  Suny   12C     88

In [ ]:
#last DICTIONARY OF DICTIONARY ITS MAIN
import pandas as pd
dict={"Marketing":{"Name":"sanjay","Age":"30","Grade":"1"},"Sales":{"Name":"yogesh","Age":"40","Grade":"2"},
      "Sports":{"Name":"umesh","Age":"45","Grade":"3"}}  #make here dictionary of dictionariessss
#point note outer keys become column and inner keys become rows please remember this point
s=pd.DataFrame(dict)
print(s)

      Marketing   Sales Sports
Name     sanjay  yogesh  umesh
Age          30      40     45
Grade         1       2      3

In [ ]:
import pandas as pd
df=pd.read_csv("/content/student - student (3).csv")
print(df)

   stu_id    name  age  gender     address
0       1   varun   30    male  chandigarh
1       2    ravi   31    male       delhi
2       3  preeti   29  female      jaipur
3       4   amrit   32    male      mumbai
4       5   pinki   28  female    banglore

In [ ]:
#DATA FRAME ATTRIBUTES
#df.index
#df.columns
#df.axes
df.dtypes
#df.size
#df.shape
#df.ndim
#df.empty
#df.values

stu_id      int64
name       object
age         int64
gender     object
address    object
dtype: object

In [ ]:
print(df.loc[:])#two row

   stu_id    name  age  gender     address
0       1   varun   30    male  chandigarh
1       2    ravi   31    male       delhi
2       3  preeti   29  female      jaipur
3       4   amrit   32    male      mumbai
4       5   pinki   28  female    banglore

In [ ]:
print(df["name"])

0     varun
1      ravi
2    preeti
3     amrit
4     pinki
Name: name, dtype: object

In [ ]:
print(df[["name","age"]])

     name  age
0   varun   30
1    ravi   31
2  preeti   29
3   amrit   32
4   pinki   28

In [ ]:
#we assign index to R1,R2,R3,R4
import pandas as pd
df=pd.read_csv("/content/student - student (3).csv")
df.index = ["R1","R2","R3","R4","R5"]
print(df)

    stu_id    name  age  gender     address
R1       1   varun   30    male  chandigarh
R2       2    ravi   31    male       delhi
R3       3  preeti   29  female      jaipur
R4       4   amrit   32    male      mumbai
R5       5   pinki   28  female    banglore

In [ ]:
print(df["name"][:]) #only single name

R1     varun
R2      ravi
R3    preeti
R4     amrit
R5     pinki
Name: name, dtype: object

In [ ]:
print(df.loc[["R1","R3","R5"],["name","age","address"]])

      name  age     address
R1   varun   30  chandigarh
R3  preeti   29      jaipur
R5   pinki   28    banglore

In [ ]:
df[df["age"]>29]

    stu_id   name  age gender     address
R1       1  varun   30   male  chandigarh
R2       2   ravi   31   male       delhi
R4       4  amrit   32   male      mumbai

In [ ]:
df[df["address"]===jaipur]

SyntaxError: invalid syntax (3119665963.py, line 1)

In [ ]:
#add new column to a DataFrame
df["Phone_no"]=[11,44,22,99,55]
print(df)

    stu_id    name  age  gender     address  Phone_no
R1       1   varun   30    male  chandigarh        11
R2       2    ravi   31    male       delhi        44
R3       3  preeti   29  female      jaipur        22
R4       4   amrit   32    male      mumbai        99
R5       5   pinki   28  female    banglore        55

In [ ]:
#rename old column name to new ome
#df=df.rename(columns={"old_column_name":"new_column_name"})
df=df.rename(columns={"Phone_no":"Phone"})
print(df)

    stu_id    name  age  gender     address  Phone
R1       1   varun   30    male  chandigarh     11
R2       2    ravi   31    male       delhi     44
R3       3  preeti   29  female      jaipur     22
R4       4   amrit   32    male      mumbai     99
R5       5   pinki   28  female    banglore     55

In [ ]:
#rename old column name to new ome
#df=df.rename(columns={"old_column_name":"new_column_name"})
df=df.rename(columns={"Phone_no":"Phone"})
print(df)

    stu_id    name  age  gender     address
R1       1   varun   30    male  chandigarh
R2       2    ravi   31    male       delhi
R3       3  preeti   29  female      jaipur
R4       4   amrit   32    male      mumbai
R5       5   pinki   28  female    banglore

In [ ]:
#DELETING A COLUMN FROM A DATAFRAME
del df["Phone"]
print(df)

    stu_id    name  age  gender     address
R1       1   varun   30    male  chandigarh
R2       2    ravi   31    male       delhi
R3       3  preeti   29  female      jaipur
R4       4   amrit   32    male      mumbai
R5       5   pinki   28  female    banglore

In [ ]:
print(df.head())

    stu_id    name  age  gender     address
R1       1   varun   30    male  chandigarh
R2       2    ravi   31    male       delhi
R3       3  preeti   29  female      jaipur
R4       4   amrit   32    male      mumbai
R5       5   pinki   28  female    banglore

In [ ]:
print(df.tail())

    stu_id    name  age  gender     address
R1       1   varun   30    male  chandigarh
R2       2    ravi   31    male       delhi
R3       3  preeti   29  female      jaipur
R4       4   amrit   32    male      mumbai
R5       5   pinki   28  female    banglore

In [ ]:
#count age above 30
print(df[df["age"]>30].count().iloc[0])

2